### ISSUE TITLE
Cannot edit or reorder items in To-do list Card from Popup

### ISSUE THREAD

**Issue by nima-1102** [thomasloven/hass-browser_mod#671]
My Home Assistant version: 2024.1.2
Browser Mod: 2.3.0
Card Mod: 3.4.2

**What I am doing:**
Try editing or reordering a to-do list card item in a browser mod popup.

**What I expected to happen:**
If I click on an item in the to-do list I should be able to edit it, or if there are multiple items in a list I should be able to rearrange them using the Resort button.

**What happened instead:**
When I click on an item in the to-do list nothing happens, when I click on the resort button the popup closes.

**Minimal** steps to reproduce:
Create button, click button, create items, try to edit or reorder items.

```yaml
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Todo List
      size: normal
      content:
        type: todo-list
        entity: todo.example
```

**Error messages from the browser console:**

```
No Message
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by smartqasa** [comment]
Same issue. Tried to open an 'frontend' issue but that was rejected.
